# Generated by Django 5.1.5 on 2025-01-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_category_categories_rename_product_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорію', 'verbose_name_plural': 'Категорії'},
        ),
    ]
