# Generated by Django 5.1.5 on 2025-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Продукт')),
                ('serial', models.CharField(max_length=50, verbose_name='Номер')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Кількість')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('invoce', models.CharField(max_length=50, verbose_name='Інвойс')),
                ('car_brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'лист замовлення ',
                'verbose_name_plural': 'листи замовлень',
            },
        ),
    ]
