# Generated by Django 5.1.5 on 2025-01-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='order',
            name='car_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Колір'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвойс'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='car_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='car_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель'),
        ),
    ]
