# Generated by Django 5.1.5 on 2025-01-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_car_brand_order_car_model_order_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='invoce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвойс'),
        ),
    ]
