# Generated by Django 5.1.5 on 2025-01-31 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'марка',
                'verbose_name_plural': 'марки',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Колір')),
                ('invoice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвойс')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.carbrand')),
            ],
            options={
                'verbose_name': 'автомобіль',
                'verbose_name_plural': 'автомобілі',
            },
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
