# Generated by Django 5.1.5 on 2025-02-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_carbrand_carmodel_delete_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Моделі'},
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.carbrand', verbose_name='Марка'),
        ),
    ]
